theme: jekyll-theme-cayman
title: NUS CRI Client Portal is Under Maintenance
description: Due to network update in NUS, NUS CRI Client Portal will be unavialable from 10 p.m. Oct 22 2020 to 8 p.m. Oct 23 , Singapore time (UTC+8).
description2: Sorry for the inconvenience caused.