theme: jekyll-theme-cayman
title: NUS CRI Client Portal is Under Maintenance
description: Due to network update in NUS, NUS CRI Client Portal will be unavialable from 10 p.m. Oct 22 2020 to 1 p.m. Oct 23 2020.
description2: Sorry for the inconvenience caused.