theme: jekyll-theme-cayman
title: CRI Client Portal is under Maintenance
description: Due to network update in NUS, CRI Client Portal will be unavialable from 10 p.m. Oct 22 2020 to 1 p.m. Oct 23 2020